config/routes.rb
Rails.application.routes.draw do
  resources :tests, except: [:index, :show, :edit, :destroy]
  
  resources :tests, only: [:edit] do
    resources :questions, except: [:index, :show]
  end

  resources :test_responses, only: [:destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]

  root 'sessions#new'

  # want to change edit/update/destroy to not have id's for tests/questions

  # Users
  get  '/users/list', to: 'users#index'
  get  '/profile', to: 'users#show'
  get  '/signup', to: 'users#new'
  post '/signedup', to: 'users#create'
  get  '/profile/edit', to: 'users#edit'
  patch  '/profile/update', to: 'users#update'
  delete '/profile/delete', to: 'users#destroy'

  # Tests
  get '/home', to: 'tests#index'
  get '/tests/:id', to: 'tests#show', as: 'take_test'
  post '/tests/:id', to: 'test_response#create', as: 'test_responses'
  delete '/tests/:id/edit/delete', to: 'tests#destroy', as: 'delete_test'
  get  '/test_results', to: 'tests#result_index'
  get  '/test_results/:id', to: 'tests#result'

  # Project Documentation
  get '/project_documentation/test_plan'

  # Sessions
  get  '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

=begin  
default paths example

get '/hotels', to: 'hotels#index'
get '/hotels/:id', to: 'hotels#show'
get '/hotels/new', to: 'hotels#new'
post '/hotels', to: 'hotels#create'
get '/hotels/:id/edit', to: 'hotels#edit'
put '/hotels/:id', to: 'hotels#update'
delete '/hotels/:id', to: 'hotels#destroy'
=end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :tests, dependent: :destroy
  has_many :test_responses, dependent: :destroy

  attr_accessor :reset_token

  before_save { self.email = email.downcase }
  VALID_NAME_REGEX = /\A[a-z][a-z\'\-]+([\ a-z][a-z\'\-]+)*\z/i
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  with_options on: :editable do    
    validates(:firstName, presence: true, length: { in: 2...50}, format: { with: VALID_NAME_REGEX })
    validates(:lastName, presence: true, length: { in: 2...50}, format: { with: VALID_NAME_REGEX })
    validates(:email, presence: true, length: { maximum: 80 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: true)
    validates(:schoolID, presence: true, numericality: { only_integer: true }, length: { is: 6 }, uniqueness: true)
  end

  with_options on: :pword do
    validates(:password, presence: true, length: { minimum: 6 }, allow_nil: true, confirmation: {case_sensitive: true})
    validates(:password_confirmation, presence: true)
  end

  # def new_email?
  #   @user = User.find(params[:id])
  #   :email != @user.email
  # end

  # def new_id?
  #   @user = User.find(params[:id])
  #   :schoolID != @user.schoolID
  # end
  
  has_secure_password
  

  # default_scope { order(firstName: :asc) }
        
  # before_create { generate_token(:auth_token) }

  # def send_password_reset 
  #     generate_token(:password_reset_token)
  #     self.password_reset_sent_at = Time.zone.now 
  #     save!
  #     UserMailer.password_reset(self).deliver 
  # end 

  # def generate_token(column)
  #     begin 
  #         self[column] = SecureRandom.urlsafe_base64
  #     end while User.exists?(column => self[column])
  # end 
  
  # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # Returns true if a password reset has expired.
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_login, except: [:new, :create]
  before_action :require_admin, only: [:index, :destroy]

  # GET /users
  # GET /users.json
  def index
    # if params[:search]
    #   search_users
    # end
    @people = User.all.order(:firstname)

    @users = @people.where(isAdmin: false)
    # @users = @users.order(:firstname)
    @admin = @people.where(isAdmin: true)
    # @admin = @admin.order(:firstname)
  end

  # add will_paginate and search_users to helper file?
  # def will_paginate
  # end
  # be able to search by first, last, or both first and last name
  # def search_users
    # if @user == User.all.find{|user| user.name.include? (params[:search])}
    #   @user = User.all.find{|user| user.name.include? (params[:search])}
    # end
    # respond_to do |format|
    #   format.js {render inline: "location.reload();" }
    # end
  # end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.isAdmin = false

    respond_to do |format|
      if @user.valid?(:editable) && @user.valid?(:pword) && @user.save
        reset_session
        log_in(@user)
        format.html { redirect_to home_path }
        format.json { render "tests/index", status: :created, location: home_path }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    if params[:Promote]
      respond_to do |format|
        if @user.update(:isAdmin => true)
          format.html { redirect_to users_list_path, notice: 'User was successfully updated.' }
          format.json { render :update, status: :ok, location: users_list_path }
        else
          format.html { render :index }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    else
      # logger.debug "before: #{@user.attributes}\n"
      @user.assign_attributes(user_params)
      # logger.debug "after: #{@user.attributes}\n"
      # logger.debug "valid?: #{@user.valid?(:editable)}\n"
      respond_to do |format|
        if @user.valid?(:editable) && @user.save
          # logger.debug "user: #{@user.attributes}"
          format.html { redirect_to profile_path(id: current_user), notice: 'User was successfully updated.' }
          format.json { render :update, status: :ok, location: profile_path(id: current_user) }
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:firstName, :lastName, :email, :password, :password_digest, :password_confirmation, :schoolID, :isAdmin)
    end
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>

<h3>Editing Profile</h3>
<br/>

<div class="row">
  <div class="col-12 col-sm-8 col-lg-6 mx-auto">
    <div class="card mx-auto border-primary">
      <div class="card-body d-grid gap-3">
        <%= form_with(model: @user, local: true, url: profile_update_path(id: current_user), class: 'mb-0') do |f| %>
          <%= render 'shared/error_user' %>

          <%= f.label :firstName, "First Name" %>
          <%= f.text_field :firstName, class: 'form-control' %>
          
          <%= f.label :lastName, "Last Name" %>
          <%= f.text_field :lastName, class: 'form-control' %>

          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control' %>
          
          <%= f.label :schoolID, "School ID" %>
          <%= f.text_field :schoolID, class: 'form-control' %>

          <div class="d-grid col-6 mx-auto">
            <%= f.submit "Save Changes", class: "btn-primary mb-0" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, "List of Users") %>
<html>
  <body>
    <!--maybe add table responsive bootstrap-->
    <div class="row">
      <div class="col-xl-5 mb-3">
        <div class="card h-100 border-primary">
          <div class="card-body container-fluid px-0" style="overflow-x:auto">
            <!--List of Admin-->
            <!--<span style= "float:left">-->
              <h2 class="card-title mb-3">Admin</h2>
   
              
              <!--search bar
              <#%= form_tag(method: :get) do %>
                <%= text_field_tag(:search, params[:search]) %>
                <%= submit_tag ("Search") %>
              <#% end %>-->

              <!--<= will_paginate %>-->
              
              <table>
                <thead>
                  <tr>
                    <!--th><#%= link_to "First Name", :sort => "firstName"%></th>
                    <th><#%= link_to "Last Name", :sort => "lastName"%></th-->
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Email</th>
                  </tr>
                </thead>
              
                <tbody>
                  <% @admin.find_each do |user| %>
                    <tr>
                      <td><%= user.firstName %></td>
                      <td><%= user.lastName %></td>
                      <td><%= user.email %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
              
              <!--<= will_paginate %>-->
              
              <!--<br>-->
            <!--</span>-->
          </div>
        </div>
      </div>
      
      <div class="col-xl-7 mb-3">
        <div class="card h-100 border-primary">
          <div class="card-body container-fluid px-0 h-100" style="overflow-x:auto">
            <!--List of Users-->
            <!--<span style= "float:right">-->
              <h2 class="card-title mb-3">Users</h2>
              
              
              <!--search bar
              <#%= form_tag(method: :get) do %>
                <%= text_field_tag(:search, params[:search]) %>
                <%= submit_tag ("Search") %>
              <#% end %>-->

              <!--<= will_paginate %>-->
              
              <table>
                <thead>
                  <tr>
                    <!--th><#%= link_to "First Name", :sort => "firstName"%></th>
                    <th><#%= link_to "Last Name", :sort => "lastName"%></th-->
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Email</th>
                    <th>School ID</th>
                    <th></th>
                  </tr>
                </thead>
              
                <tbody>
                  <% @users.find_each do |user| %>
                    <tr>
                      <td><%= user.firstName %></td>
                      <td><%= user.lastName %></td>
                      <td><%= user.email %></td>
                      <td><%= user.schoolID %></td>
                      <td style="padding: 0px 10px">
                        <%= link_to 'Promote User', profile_update_path(id: user.id, Promote: true), method: :patch, params: {Promote: true}, class: "promote btn-primary text-white", data: { confirm: 'Are you sure you want to promote this user to be an admin?' } %>
                      </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
              <!--<= will_paginate %>-->
            <!--</span>-->
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<h1>Sign up</h1>
<br/>

<div class="row">
  <div class="col-10 col-md-8 col-lg-6 mx-auto">
    <div class="card mx-auto border-primary">
      <div class="card-body d-grid gap-3">
        <%= form_with(model: @user, local: true, url: signedup_path(@user), class: 'mb-0') do |f| %>
          <%= render 'shared/error_user' %>
          
          <%= f.label :firstName, "First Name" %>
          <%= f.text_field :firstName, class: 'form-control' %>
          
          <%= f.label :lastName, "Last Name" %>
          <%= f.text_field :lastName, class: 'form-control' %>

          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control' %>
          
          <%= f.label :schoolID, "School ID" %>
          <%= f.text_field :schoolID, class: 'form-control' %>

          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control' %>

          <%= f.label :password_confirmation, "Password Confirmation" %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
          
          <div class="d-grid col-6 mx-auto">
            <%= f.submit "Create My Account", class: "btn-primary mb-0" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, "User Profile") %>

<h3>User Profile</h3>
</br>
<!--usure of what this is-->
<!--<p id="notice"><#%= notice %></p>-->
<div class="row">
  <div class="col-12 col-sm-8 col-lg-6 mx-auto">
    <div class="card border-primary px-0">
      <div class="card-body container-fluid px-0" style="overflow-x:auto">
        <table>
          <tbody>
            <tr>
              <th class="p-2">Name:</th>
              <td class="p-2"><%= @user.firstName %> <%= @user.lastName %></td>
            </tr>
            <tr>
              <th class="p-2">Email:</th>
              <td class="p-2"><%= @user.email %></td>
            </tr>
            <tr>
              <th class="p-2">School ID:</th>
              <td class="p-2"><%= @user.schoolID %></td>
            </tr>
            <%
=begin%>
 <tr>
              <th class="p-2">Role:</th>
              <td class="p-2">
                <% if @user.isAdmin == true %>
                  Admin
                <% else %>
                  User
                <% end %>
              </td>
            </tr> 
<%
=end%>
          </tbody>
        </table>
        <div class="d-grid col-6 mx-auto mt-3">
          <%= link_to 'Edit Profile', profile_edit_path(id: current_user), class: 'btn-primary' %>
        </div>
      </div>
    </div>
  </div>
</div>