config/routes.rb
Rails.application.routes.draw do
  resources :tests, except: [:index, :show, :edit, :destroy]
  
  resources :tests, only: [:edit] do
    resources :questions, except: [:index, :show]
  end

  resources :test_responses, only: [:destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]

  root 'sessions#new'

  # want to change edit/update/destroy to not have id's for tests/questions

  # Users
  get  '/users/list', to: 'users#index'
  get  '/profile', to: 'users#show'
  get  '/signup', to: 'users#new'
  post '/signedup', to: 'users#create'
  get  '/profile/edit', to: 'users#edit'
  patch  '/profile/update', to: 'users#update'
  delete '/profile/delete', to: 'users#destroy'

  # Tests
  get '/home', to: 'tests#index'
  get '/tests/:id', to: 'tests#show', as: 'take_test'
  post '/tests/:id', to: 'test_response#create', as: 'test_responses'
  delete '/tests/:id/edit/delete', to: 'tests#destroy', as: 'delete_test'
  get  '/test_results', to: 'tests#result_index'
  get  '/test_results/:id', to: 'tests#result'

  # Project Documentation
  get '/project_documentation/test_plan'

  # Sessions
  get  '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

=begin  
default paths example

get '/hotels', to: 'hotels#index'
get '/hotels/:id', to: 'hotels#show'
get '/hotels/new', to: 'hotels#new'
post '/hotels', to: 'hotels#create'
get '/hotels/:id/edit', to: 'hotels#edit'
put '/hotels/:id', to: 'hotels#update'
delete '/hotels/:id', to: 'hotels#destroy'
=end

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-dark navbar-expand-lg fixed-top">
  <div class="container-fluid py-2 px-3">
    <% if logged_in? %>
      <%= link_to "Inquest", home_path, class: "navbar-brand m-0 p-0", style: "font-size: 20pt; font-weight: bold" %>
    <% else %>
      <%= link_to "Inquest", root_path, class: "navbar-brand m-0 p-0", style: "font-size: 20pt; font-weight: bold" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon btn"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
      <ul class="navbar-nav nav-pills">
        <% if logged_in? %>
          <li><%= link_to "Home", home_path, class: "nav-link" %></li>
          <% if admin? %>
            <li><%= link_to "Create A Test", new_test_path, class: "nav-link" %></li>
            <li><%= link_to "Users", users_list_path, class: "nav-link" %></li>
            </li>
            <!--li class="dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="documentation" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Documentation
              </a>
              <ul class="dropdown-menu dropdown-menu-dark" style="background-color: #000080; padding:0; font-size: 14pt" aria-labelledby="documentation">
                <li><#%= link_to "Test Plan", project_documentation_test_plan_path, class: "dropdown-item m-0" %></li>
                <li></li>
                <li></li>
              </ul>
            </li-->
          <% else %>
            <li><%= link_to "View Test Results", test_results_path, class: "nav-link" %></li>
          <% end %>
            <li><%= link_to "Profile", profile_path(id: current_user), class: "nav-link" %></li>
            <li><%= link_to "Log Out", logout_path, method: :delete, class: "nav-link" %></li>
        <% else %>
          <li><%= link_to "Log In", login_path, class: "nav-link" %></li>
          <li><%= link_to "Sign Up", signup_path, class: "nav-link" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<html lang="en">
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'  %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'global', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!--#%= controller.controller_name %-->
    <% if @doc == "test_documentation" %>
      <%= stylesheet_link_tag 'project_documentation', media: 'all', 'data-turbolinks-track': 'reload' %>
    <% end %>
    <%= render 'layouts/shim' %>
  </head>
  
  <body>
    <header>
      <%= render 'layouts/header' %>
    </header>
    <div class="container-fluid app-load">
      <%= yield %>
    </div>
  </body>
</html>